# Generated by Django 6.0.3 on 2026-03-18 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('is_active', models.CharField(default='Y', max_length=1)),
                ('added_by', models.IntegerField()),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.IntegerField()),
                ('update_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='SubCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.CharField(default='Y', max_length=1)),
                ('added_by', models.IntegerField()),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.IntegerField()),
                ('update_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'sub_categories',
            },
        ),
    ]
