# Generated by Django 6.0.3 on 2026-03-22 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_categories_name_alter_categories_update_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('secret_code', models.CharField(max_length=50, unique=True)),
                ('is_active', models.CharField(default='Y', max_length=1)),
                ('added_by', models.IntegerField()),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.IntegerField()),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'invitations',
            },
        ),
    ]
