# Generated by Django 6.0.3 on 2026-03-24 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_invitations'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.IntegerField()),
                ('sub_category_id', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.CharField(default='Y', max_length=1)),
                ('added_by', models.IntegerField()),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.IntegerField()),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'case_list',
            },
        ),
        migrations.CreateModel(
            name='DonationBeneficiaries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beneficiary_name', models.CharField(max_length=100)),
                ('guardian_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('mobile_number', models.CharField(max_length=50)),
                ('is_active', models.CharField(default='Y', max_length=1)),
                ('added_by', models.IntegerField()),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.IntegerField()),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'beneficiaries',
            },
        ),
        migrations.CreateModel(
            name='DonationGiven',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.IntegerField()),
                ('amount', models.FloatField(default=0)),
                ('is_active', models.CharField(default='Y', max_length=1)),
                ('added_by', models.IntegerField()),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.IntegerField()),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'donation_given',
            },
        ),
        migrations.CreateModel(
            name='DonationReceived',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('payment_method', models.CharField(max_length=25)),
                ('amount', models.FloatField(default=0)),
                ('service_cost', models.FloatField(default=0)),
                ('is_active', models.CharField(default='Y', max_length=1)),
                ('added_by', models.IntegerField()),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.IntegerField()),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'donation_received',
            },
        ),
    ]
