# Generated by Django 6.0.3 on 2026-03-24 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_caserecords_donationbeneficiaries_donationgiven_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationreceived',
            name='notes',
            field=models.CharField(default='', max_length=255),
        ),
    ]
