# Generated by Django 6.0.3 on 2026-03-25 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_donationreceived_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationreceived',
            name='category_id',
            field=models.IntegerField(default=0),
        ),
    ]
