# Generated by Django 6.0.3 on 2026-03-25 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_donationreceived_category_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='caserecords',
            name='amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='caserecords',
            name='beneficiary_id',
            field=models.IntegerField(default=0),
        ),
    ]
