# Generated by Django 6.0.3 on 2026-03-25 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_caserecords_amount_caserecords_beneficiary_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationgiven',
            name='notes',
            field=models.CharField(default='', max_length=255),
        ),
    ]
