# Generated by Django 6.0.3 on 2026-03-27 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_donationgiven_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='caserecords',
            name='facebook_embed_code',
            field=models.TextField(blank=True, null=True),
        ),
    ]
